apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
  namespace: edu-pavel-chepik
  labels:
    app: django
    component: clearsessions
spec:
  schedule: "0 2 * * *"        # ежедневно в 2:00
  startingDeadlineSeconds: 3600
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: clearsessions
            image: ou7ro/django-site:0dbd3a8
            command: ["python", "manage.py", "clearsessions"]
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: dsn
            - name: PGSSLMODE
              value: "verify-full"
            - name: DJANGO_SECRET_KEY
              value: "v3c0syb6*6b*at-4v(f4#1kihrf$1#uu1o0p#24e%%w)=i&$e%"
            - name: DJANGO_DEBUG
              value: "False"
            resources:
              requests:
                memory: "64Mi"
                cpu: "100m"
              limits:
                memory: "128Mi"
                cpu: "200m"
            volumeMounts:
            - name: postgres-cert
              mountPath: /root/.postgresql
              readOnly: true
          volumes:
          - name: postgres-cert
            secret:
              secretName: postgres
              items:
              - key: root.crt
                path: root.crt
          restartPolicy: Never