apiVersion: v1
kind: Pod
metadata:
  name: psql-test
  namespace: edu-pavel-chepik
spec:
  containers:
  - name: psql
    image: postgres:alpine
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    env:
    - name: PGHOST
      valueFrom:
        secretKeyRef:
          name: postgres
          key: host
    - name: PGPORT
      valueFrom:
        secretKeyRef:
          name: postgres
          key: port
    - name: PGUSER
      valueFrom:
        secretKeyRef:
          name: postgres
          key: username
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres
          key: password
    - name: PGDATABASE
      valueFrom:
        secretKeyRef:
          name: postgres
          key: name
    - name: PGSSLMODE
      value: "verify-full"
    volumeMounts:
    - name: postgres-cert
      mountPath: /root/.postgresql
      readOnly: true
  volumes:
  - name: postgres-cert
    secret:
      secretName: postgres
      items:
      - key: root.crt
        path: root.crt